version: "3"
services:
  #######################################################
  #  Gateway
  #######################################################
  gateway:
    hostname: gateway
    restart: on-failure
    build:
      context: ./
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "80:80"
    links:
      - products
      - categories
    depends_on:
      - products
      - categories
    networks:
      - aeon
  #######################################################
  #  Products
  #######################################################
  products:
    hostname: products
    build:
      context: ./
      dockerfile: src/Services/Products/Dockerfile
    networks:
      - aeon
  #######################################################
  #  Categories
  #######################################################
  categories:
    hostname: categories
    build:
      context: ./
      dockerfile: src/Services/Categories/Dockerfile
    networks:
      - aeon

networks:
  aeon:
    name: aeon
