version: "3"
services:
  #######################################################
  #  Gateway
  #######################################################
  gateway:
    hostname: gateway
    image: "martstech/aeon-gateway"
    mem_limit: 128m
    ports:
      - "80:80"
    links:
      - weather
    depends_on:
      - weather
    networks:
      - aeon
  #######################################################
  #  Weather
  #######################################################
  weather:
    hostname: weather
    image: "martstech/aeon-weather"
    mem_limit: 128m
    networks:
      - aeon

networks:
  aeon:
    name: aeon
