version: "3"
services:
  #######################################################
  #  Gateway
  #######################################################
  gateway:
    hostname: gateway
    restart: on-failure
    build:
      context: ./
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "80:80"
    links:
      - weather
    depends_on:
      - weather
    networks:
      - aeon
  #######################################################
  #  Weather
  #######################################################
  weather:
    hostname: weather
    build:
      context: ./
      dockerfile: src/Services/Weather/Dockerfile
    networks:
      - aeon

networks:
  aeon:
    name: aeon
