version: "3"
services:
  #######################################################
  #  Gateway
  #######################################################
  gateway:
    hostname: gateway
    image: "martstech/aeon-gateway"
    mem_limit: 128m
    ports:
      - "80:80"
    links:
      - products
      - categories
    depends_on:
      - products
      - categories
    networks:
      - aeon
  #######################################################
  #  Products
  #######################################################
  products:
    hostname: products
    image: "martstech/aeon-products"
    mem_limit: 128m
    networks:
      - aeon
  #######################################################
  #  Categories
  #######################################################
  categories:
    hostname: categories
    image: "martstech/aeon-categories"
    mem_limit: 128m
    networks:
      - aeon

networks:
  aeon:
    name: aeon
