version: "3"
services:
  #######################################################
  #  Gateway
  #######################################################
  gateway:
    hostname: gateway
    image: "martstech/aeon-gateway"
    mem_limit: 128m
    ports:
      - "80:80"
    links:
      - catalog
    depends_on:
      - catalog
    networks:
      - aeon
  #######################################################
  #  Catalog
  #######################################################
  catalog:
    hostname: catalog
    image: "martstech/aeon-catalog"
    mem_limit: 128m
    networks:
      - aeon

networks:
  aeon:
    name: aeon
