// <auto-generated />
using System;
using Catalog.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20230404164153_Ratings")]
    partial class Ratings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Catalog.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9966870c-9dc8-483e-b64c-a5f88b3030c2"),
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = new Guid("6add9014-ce94-4bdb-9755-960586362474"),
                            Name = "Vegetables"
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Comments.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Catalog.Domain.Comments.Upvote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.ToTable("Upvotes");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20e33b06-18da-4685-8b54-e282072e2be9"),
                            CategoryId = new Guid("9966870c-9dc8-483e-b64c-a5f88b3030c2"),
                            Description = "Orange fruit",
                            Discount = 0m,
                            Image = "",
                            Price = 2m,
                            Quantity = 2,
                            Title = "Orange"
                        },
                        new
                        {
                            Id = new Guid("a228e017-1770-4fde-abe3-699e015ad74b"),
                            CategoryId = new Guid("9966870c-9dc8-483e-b64c-a5f88b3030c2"),
                            Description = "Red fruit",
                            Discount = 0m,
                            Image = "",
                            Price = 3m,
                            Quantity = 3,
                            Title = "Apple"
                        },
                        new
                        {
                            Id = new Guid("7b72248b-7176-4e12-b9b1-6bd8cd6395fc"),
                            CategoryId = new Guid("6add9014-ce94-4bdb-9755-960586362474"),
                            Description = "Green vegetable",
                            Discount = 0m,
                            Image = "",
                            Price = 4m,
                            Quantity = 1,
                            Title = "Cucumber"
                        },
                        new
                        {
                            Id = new Guid("69e1eb16-1f07-4ee4-9607-3b12af7fd09d"),
                            CategoryId = new Guid("6add9014-ce94-4bdb-9755-960586362474"),
                            Description = "Red vegetable",
                            Discount = 0m,
                            Image = "",
                            Price = 1m,
                            Quantity = 6,
                            Title = "Tomato"
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Ratings.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Catalog.Domain.Comments.Comment", b =>
                {
                    b.HasOne("Catalog.Domain.Products.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Catalog.Domain.Comments.Upvote", b =>
                {
                    b.HasOne("Catalog.Domain.Comments.Comment", "Comment")
                        .WithMany("Upvotes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Product", b =>
                {
                    b.HasOne("Catalog.Domain.Categories.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Catalog.Domain.Ratings.Rating", b =>
                {
                    b.HasOne("Catalog.Domain.Products.Product", "Product")
                        .WithMany("Ratings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Catalog.Domain.Categories.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Catalog.Domain.Comments.Comment", b =>
                {
                    b.Navigation("Upvotes");
                });

            modelBuilder.Entity("Catalog.Domain.Products.Product", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
