// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Weather.Persistence;

#nullable disable

namespace Weather.Persistence.Migrations
{
    [DbContext(typeof(DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Weather.Domain.Forecasts.Forecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasMaxLength(3)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Forecasts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e462234-1e19-4a00-ba6b-e49930c571a6"),
                            Date = new DateOnly(2023, 1, 12),
                            Summary = "Sweltering",
                            TemperatureC = -8
                        },
                        new
                        {
                            Id = new Guid("c08dda04-c47f-4879-ba77-66ae6ed3a4c1"),
                            Date = new DateOnly(2023, 1, 13),
                            Summary = "Mild",
                            TemperatureC = 32
                        },
                        new
                        {
                            Id = new Guid("384272b5-1a6f-4aaf-8c5c-2628f73dfd49"),
                            Date = new DateOnly(2023, 1, 14),
                            Summary = "Bracing",
                            TemperatureC = 39
                        },
                        new
                        {
                            Id = new Guid("b46b2c2b-90a3-423e-b59e-79e084ac25ab"),
                            Date = new DateOnly(2023, 1, 15),
                            Summary = "Chilly",
                            TemperatureC = 42
                        },
                        new
                        {
                            Id = new Guid("ab8db0e2-ae0a-4657-98b7-4beb9cb37bf1"),
                            Date = new DateOnly(2023, 1, 16),
                            Summary = "Cool",
                            TemperatureC = -9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
